/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subjects */
        get: operations["subjects_api_v1_demo_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Session */
        post: operations["close_session_api_v1_sessions__session_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/runs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Run */
        post: operations["stream_run_api_v1_sessions__session_id__runs_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Status */
        get: operations["provider_status_api_v1_providers_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorDTO */
        ApiErrorDTO: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Run Id */
            run_id?: string | null;
        };
        /** CatalogDTO */
        CatalogDTO: {
            /** Knowledge */
            knowledge: components["schemas"]["KnowledgeSourceDTO"][];
            /** Tools */
            tools: components["schemas"]["ToolDTO"][];
        };
        /** ClosedSessionDTO */
        ClosedSessionDTO: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Closed At
             * Format: date-time
             */
            closed_at: string;
            /** Close Run Id */
            close_run_id: string | null;
            terminal_event: components["schemas"]["RunEventDTO"] | null;
        };
        /** CreatedSessionDTO */
        CreatedSessionDTO: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Subject Id */
            subject_id: string;
            /** Subject Label */
            subject_label: string;
            /** Demo Session Token */
            demo_session_token: string;
            /**
             * Token Expires At
             * Format: date-time
             */
            token_expires_at: string;
            /** Source */
            source: string;
        };
        /** HealthDTO */
        HealthDTO: {
            /** Status */
            status: string;
        };
        /** KnowledgeSourceDTO */
        KnowledgeSourceDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
        };
        /** MessageDTO */
        MessageDTO: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Source */
            source: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** ProviderDTO */
        ProviderDTO: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
        };
        /** ProviderStatusDTO */
        ProviderStatusDTO: {
            /** Providers */
            providers: components["schemas"]["ProviderDTO"][];
        };
        /** RunDTO */
        RunDTO: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Status */
            status: string;
            /** Intent */
            intent: string | null;
            /** Agent Path */
            agent_path: string | null;
            /** Error Code */
            error_code: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** RunEventDTO */
        RunEventDTO: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** SessionDTO */
        SessionDTO: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Subject Id */
            subject_id: string;
            /**
             * Token Expires At
             * Format: date-time
             */
            token_expires_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Messages */
            messages: components["schemas"]["MessageDTO"][];
        };
        /** SubjectDTO */
        SubjectDTO: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Role */
            role: string;
        };
        /** ToolDTO */
        ToolDTO: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
        };
    };
    health_ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    subjects_api_v1_demo_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDTO"][];
                };
            };
            /** @description CloudAgent API 错误 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "subject_id": "demo-alice"
                 *     }
                 */
                "application/json": {
                    /**
                     * Subject Id
                     * @description 合成演示身份 ID，可从 /api/v1/demo/subjects 获取
                     */
                    subject_id: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedSessionDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header: {
                /** @description 会话凭据 */
                "x-demo-session-token": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    close_session_api_v1_sessions__session_id__close_post: {
        parameters: {
            query?: never;
            header: {
                /** @description 会话凭据 */
                "x-demo-session-token": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosedSessionDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    stream_run_api_v1_sessions__session_id__runs_stream_post: {
        parameters: {
            query?: never;
            header: {
                /** @description 会话凭据 */
                "x-demo-session-token": string;
                /** @description 每次新消息使用的 UUID 幂等键 */
                "idempotency-key": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "message": "产品支持哪些部署版本？"
                 *     }
                 */
                "application/json": {
                    /**
                     * Message
                     * @description 用户消息；NFC 规范化并裁剪后须为 1 至 4,000 个码点
                     */
                    message: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description CloudAgent API 错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header: {
                /** @description 会话凭据 */
                "x-demo-session-token": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    get_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header: {
                /** @description 会话凭据 */
                "x-demo-session-token": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventDTO"][];
                };
            };
            /** @description CloudAgent API 错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
            /** @description CloudAgent API 错误 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDTO"];
                };
            };
        };
    };
    provider_status_api_v1_providers_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatusDTO"];
                };
            };
        };
    };
    catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogDTO"];
                };
            };
        };
    };
}
